
--10_1
--DEPT 테이블을 복사해서 DEPT_TEMP 테이블을 만들기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

--10_2 DEPT_TEMP 테이블 전체 열 조회
SELECT * FROM DEPT_TEMP;

-- DROP TABLE 테이블 이름; 테이블을 삭제하는 명령어

--10_3
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES (50,'DATABASE','SEOUL');

SELECT * FROM DEPT_TEMP;

--10_4
--지정할 컬럼을 생략
--값 입력은 테이블에 정의된 컬럼 순서대로 모든 값을 입력해야 함( 비 권고)
INSERT INTO DEPT_TEMP
VALUES (60,'NETWORK','BUSAN');

SELECT * FROM DEPT_TEMP;

--10_5
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES (70 , 'WEB',NULL);

SELECT * FROM DEPT_TEMP;

--10_6
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES  (80,'MOBILE','');

SELECT * FROM DEPT_TEMP;

--10_7 컬럼을 지정하지 않은 묵시적 입력 방식
INSERT INTO DEPT_TEMP (DEPTNO,LOC)
VALUES (90,'INCHEON');

SELECT * FROM DEPT_TEMP;

--10_8 EMP 테이블을 복사해서 EMP_TEMP 테이블 만들기
CREATE TABLE EMP_TEMP
AS SELECT *
FROM EMP
WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

--10_9

INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'2001/01/01',5000,1000,10);

SELECT * FROM EMP_TEMP;

--10_10
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_EX
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'1994-01-05',5000,1000,10);

SELECT * FROM EMP_TEMP;

--10_11
--YYYY/MM/DD나 YYYY-MM-DD, YYYY*MM*DD 등 순서가 맞으면 입력되나 다르면 오류
--일/월/년도 방식으로 하면 오류뜸
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (2111,'이순신','MANAGER',9999,'07/01/2001',4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_12
--TO_DATE 함수를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (2111,'이순신','MANAGER',9999,
        TO_DATE('07/01/2001','DD/MM/YYYY'),4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_13
--SYSDATE 함수
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (3111,'심청이','MANAGER',9999,SYSDATE,4000,NULL,30);

SELECT * FROM EMP_TEMP;

--10_14
--기존 테이블의 데이터를 INSERT할시에는 VALUES대신 SELECT 서브쿼리 사용
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

COMMIT;
--데이터 조작어인 INSERT는 COMMIT 하지 않으면 DB에서 나가면 사라짐