
--10_1
--DEPT 테이블을 복사해서 DEPT_TEMP 테이블을 만들기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

--10_2 DEPT_TEMP 테이블 전체 열 조회
SELECT * FROM DEPT_TEMP;

-- DROP TABLE 테이블 이름; 테이블을 삭제하는 명령어

--10_3
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES (50,'DATABASE','SEOUL');

SELECT * FROM DEPT_TEMP;

--10_4
--지정할 컬럼을 생략
--값 입력은 테이블에 정의된 컬럼 순서대로 모든 값을 입력해야 함( 비 권고)
INSERT INTO DEPT_TEMP
VALUES (60,'NETWORK','BUSAN');

SELECT * FROM DEPT_TEMP;

--10_5
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES (70 , 'WEB',NULL);

SELECT * FROM DEPT_TEMP;

--10_6
INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
VALUES  (80,'MOBILE','');

SELECT * FROM DEPT_TEMP;

--10_7 컬럼을 지정하지 않은 묵시적 입력 방식
INSERT INTO DEPT_TEMP (DEPTNO,LOC)
VALUES (90,'INCHEON');

SELECT * FROM DEPT_TEMP;


--10_8 EMP 테이블을 복사해서 EMP_TEMP 테이블 만들기
CREATE TABLE EMP_TEMP
AS SELECT *
FROM EMP
WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

--10_9

INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'2001/01/01',5000,1000,10);

SELECT * FROM EMP_TEMP;

--10_10
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_EX
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'1994-01-05',5000,1000,10);

SELECT * FROM EMP_TEMP;

--10_11
--YYYY/MM/DD나 YYYY-MM-DD, YYYY*MM*DD 등 순서가 맞으면 입력되나 다르면 오류
--일/월/년도 방식으로 하면 오류뜸
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (2111,'이순신','MANAGER',9999,'07/01/2001',4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_12
--TO_DATE 함수를 사용하여 날짜 데이터 입력하기
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (2111,'이순신','MANAGER',9999,
        TO_DATE('07/01/2001','DD/MM/YYYY'),4000,NULL,20);

SELECT * FROM EMP_TEMP;

--10_13
--SYSDATE 함수
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (3111,'심청이','MANAGER',9999,SYSDATE,4000,NULL,30);

SELECT * FROM EMP_TEMP;

--10_14
--기존 테이블의 데이터를 INSERT할시에는 VALUES대신 SELECT 서브쿼리 사용
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

COMMIT;
--데이터 조작어인 INSERT는 COMMIT 하지 않으면 DB에서 나가면 사라짐

--10_15 (데이터 수정하기)
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;


--10_16
--모든 행의 LOC컬럼을 'SEOUL' (WHERE 조건이 없어서)
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

--10_17 ROLLBACK
--UPDATE 명령어 실행 이전 상태로 돌아감
ROLLBACK;

SELECT * FROM DEPT_TEMP2;

--10_18
--WHERE절로 UPDATE행 제한
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE',
    LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--10_19
UPDATE DEPT_TEMP2
SET (DNAME,LOC) = (SELECT DNAME,LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--10_20 (19번하고 결과값이 같음)
UPDATE DEPT_TEMP2
SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
    LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--10_21
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS');

SELECT * FROM DEPT_TEMP2;

--10_22
DROP TABLE EMP_TEMP2; --테이블 삭제 (DDL로 자동 COMMIT)

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--10_23
DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

--10_24
--급여 등급이 3,급여가 1400~2000 사이에 있는 30번 부서의 사원들만 삭제
DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E ,SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 3
                AND E.DEPTNO = 30);
                
SELECT * FROM EMP_TEMP2;

ROLLBACK;

--10_25 테이블에 있는 전체 데이터 삭제하기
--데이터는 사라졌으나 테이블은 존재
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;

--10_quiz

CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

INSERT INTO CHAP10HW_DEPT (DEPTNO,DNAME,LOC)
VALUES (50,'ORACLE','BUSAN');

SELECT * FROM CHAP10HW_DEPT;