DROP TABLE DEPT_TCL;
--11_1
CREATE TABLE DEPT_TCL
AS SELECT * FROM DEPT; --새로운 트랜잭션 시작(DDL CREATE사용)

SELECT * FROM DEPT_TCL;

--11_2

INSERT INTO DEPT_TCL
VALUES (50,'DATABASE','SEOUL');

UPDATE DEPT_TCL
SET LOC = 'BUSAN'
WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL
WHERE DNAME = 'RESEARCH';

SELECT * FROM DETP_TCL;

--11_3
ROLLBACK;
SELECT * FROM DETP_TCL;

--11_4
INSERT INTO DEPT_TCL VALUES (50,'NETWORK','SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;
DELETE FROM DEPT_TCL WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'DATABASE';
SELECT * FROM DEPT_TCL;
--트랜잭션 반영 명령어인 COMMIT이나 DDL/DCL이 실행 안되어 영구 반영은 안됨

--11_5
--영구히 반영
COMMIT; --현재의 TRANSACTION 상태의 DML을 영구 반영하고 새로운 TRANSACTION시작

SELECT * FROM DEPT_TCL;

--11_7
DELETE FROM DEPT_TCL
WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL; --DEVELOPER에서 확인
SELECT * FROM DEPT_TCL; --SQLPLUS로는 변경 사항 안보임 (트랜잭션 COMMIT실행 안되어서)

--11_8
COMMIT; --트랜잭션 완료(영구보전)이후에는 다른 세션에서도 작업 가능

SELECT * FROM DEPT_TCL; --SQL DEVELOPER
SELECT * FROM DEPT_TCL; --SQLPLUS COMMIT으로 영구 반영되어 보임

--11_9
SELECT * FROM DEPT_TCL;
SELECT * FROM DEPT_TCL;

--11_10
UPDATE DEPT_TCL SET LOC = 'SEOUL'
WHERE DEPTNO = 30;

SELECT * FROM DEPT_TCL;

--11_11
--다른 세션의 작업이 트랜잭션 처리가 안되어 LOCK상태이므로 작업ㅇ르 처리 안하고 대기를 함
--SQLPLUS에서 작업
UPDATE DEPT_TCL SET DNAME = 'DATABASE'
WHERE DEPTNO = 30;

--11_12
COMMIT;

--11_13
SELECT * FROM DEPT_TCL; --섹션A의 결과는 아직 변경이 안됨

--11_14
COMMIT; --SQLPLUS에서 실행

--11_15
SELECT * FROM DEPT_TCL; --SQLPLUS에서 COMMIT완료 후 DNAME이 변경

