--DDL은 기존의 트랙잭션을 자동 COMMIT하고 새로운 트랜잭션을 시작
--12_1
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

DESC EMP_DDL;
DESCRIBE EMP_DDL; --약어는 DESC

--12_2
--서브쿼리 사용시 AS 키워드 사용
CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;

DESC DEPT_DDL;


DROP TABLE DEPT_DDL;
--12_3
SELECT * FROM DEPT_DDL;

SELECT * FROM DEPT;
DELETE FROM DEPT
WHERE DNAME = 'DATABASE';
COMMIT;

SELECT * FROM DEPT_DDL;

--12_4
DROP TABLE EMP_DDL_30;

CREATE TABLE EMP_DDL_30
AS SELECT * FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_DDL_30;

--12_5
--서브쿼리의 SELECT절의 컬럼과 같은 구조를 가진 테이블을 만들고 데이터는 가져오지 않음
DROP TABLE EMPDEPT_DDL;

CREATE TABLE EMPDEPT_DDL
AS SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,D.DEPTNO,D.DNAME,D.LOC
FROM EMP E,DEPT D
WHERE 1<>1;

SELECT * FROM EMPDEPT_DDL;

--12_6

CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

--12_7
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20); --ADD는 컬럼 추가

SELECT * FROM EMP_ALTER;

--12_8
--열 이름을 변경하는 RENAME COLUMN
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

--12_9
--열의 자료형 변경은 MODIFY
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

SELECT * FROM EMP_ALTER;

--12_10
--열의 데이터 삭제
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

--12_11
--테이블 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;

--12_12
--테이블 변경전 이름은 사용안됨
DESC EMP_ALTER;

--12_13
--변경된 테이블
SELECT * FROM EMP_RENAME;

--12_14
--DDL이므로 AUTO COMMIT이 일어나 ROLLBACK안됨
--데이터만 영구 삭제(WHERE없는 DELETE조작문은 ROLLBACK가능)
TRUNCATE TABLE EMP_RENAME;
SELECT * FROM EMP_RENAME;

--12_15
--테이블 삭제
DROP TABLE EMP_RENAME;

--12_16
DESC EMP_RENAME;