
--13_1
--모든 데이터 사전 테이블 조회
SELECT * FROM DICT;

--13_2
SELECT * FROM DICTIONARY;

--13_3
--접속 계정의 데이터 객체 조회
SELECT TABLE_NAME --컬럼명
FROM USER_TABLES; --접속 계정관련 테이블

--13_4
--SCOTT계정이 사용할 수 있는 객체 정보 조회
SELECT OWNER,TABLE_NAME
FROM ALL_TABLES; --접속 계정과 접속 계정이 허가받은 일반 테이블

--13_5
SELECT * FROM DBA_TABLES; --관리자 권한을 가진 계정에 관련된 테이블
--SCOTT계정으로 조회시는 안됨

--13_6
--SYSTEM계정으로 접속 조회시에만 보이는 DBA관련 테이블
SELECT * FROM DBA_TABLES;

--13_7
--SYSTEM계정으로 접속 조회시에만 보임
--SCOTT계정 조회
SELECT * FROM DBA_USERS
WHERE USERNAME = 'SCOTT';

--13_8
--SCOTT 계정이 소유한 인덱스 정보 알아보기
SELECT *FROM USER_INDEXES;

--13_9
SELECT * FROM USER_IND_COLUMNS; --INDEX객체를 사용하는 컬럼 정보

--13_10
CREATE INDEX IDX_EMP_SAL
        ON EMP(SAL); --EMP테이블의 SAL컬럼에 인덱스 부여
        
--13_11
SELECT * FROM USER_IND_COLUMNS;

--13_12
--INDEX 삭제
DROP INDEX IDX_EMP_SAL;

--13_13
SELECT * FROM USER_IND_COLUMNS;

--13_14
--SYSTEM계정으로 VIEW를 만들 권한 부여
--GRANT는 DCL(데이터 제어 언어로 권한 부여)
--권한 회수는 REVOKE
GRANT CREATE VIEW TO SCOTT;

--13_15
--VIEW생성 (AS SELECT 로 데이터까지 복사)
--뷰는 물리적인 데이터 저장소는 아님
CREATE VIEW VW_EMP20
AS (SELECT EMPNO,ENAME,JOB,DEPTNO FROM EMP WHERE DEPTNO = 20);

--13_16
SELECT * FROM USER_VIEWS; --VIEW 관련 데이터 사전

--13_17
SELECT VIEW_NAME,TEXT_LENGTH,TEXT
FROM USER_VIEWS;

--13_18
SELECT * FROM VW_EMP20;

--13_19
--VIEW 삭제
DROP VIEW VW_EMP20;
SELECT * FROM USER_VIEWS;

--13_20
--SELECT한 결과 순서대로 ROWNUM부여
SELECT ROWNUM, E.*
FROM EMP E;

--13_21
--ROWNUM은 SELECT시 부여되고 ORDER BY는 마지막에 실행되므로 ROWNUM은 원래 번호 가짐
SELECT ROWNUM, E.*
FROM EMP E
ORDER BY SAL DESC;

--13_22
--인라인 뷰 (서브쿼리 사용)
--TOP-N방식의 서브쿼리사용 인라인 뷰로 사전에 정렬한 서브쿼리 결과 객체를 SELECT하면
--정렬 상태된  ROWNUM가 부여된다
SELECT ROWNUM, E.*
FROM (SELECT * FROM EMP E
        ORDER BY SAL DESC) E;
        
--13_23
--인라인 뷰 (WITH 절 사용)
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM,E.*
FROM E;

--13_24
--인라인뷰로 TOP-N 추출 (서브쿼리 사용)
SELECT ROWNUM,E.*
FROM (SELECT * FROM EMP E
        ORDER BY SAL DESC) E
WHERE ROWNUM <= 3;

--13_25
--인라인뷰로 TOP-N 추출 (WITH절 사용)
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM,E.*
FROM E
WHERE ROWNUM <= 3;

--13_26
--시퀀스 실습용 테이블 생성
CREATE TABLE DEPT_SEQUENCE
AS SELECT * FROM DEPT
WHERE 1<>1;

SELECT * FROM dept_sequence;

--13_27
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2; --게시판 생성시 MINVALUE 0 , NOCACHE 만 사용

--13_28
--생성한 시퀀스 확인하기
SELECT * FROM USER_SEQUENCES;

--13_29
--시퀀스에서 생성한 순번을 사용한 INSERT문 실행하기
INSERT INTO dept_sequence (DEPTNO,DNAME,LOC)
VALUES (seq_dept_sequence.nextval,'DATABASE','SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--13_30
--가장 마지막으로 생성된 시퀀스 확인하기
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

--13_32
--ALTER 명령어로 시퀀스 옵션 수정하기
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;

--13_33
--수정된 시퀀스 확인하기
SELECT * FROM USER_SEQUENCES;

--13_34
--수정한 시퀀스 INSERT문 사용
INSERT INTO DEPT_SEQUENCE (DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');

SELECT * FROM DEPT_SEQUENCE;
--최대값 99 이상이 되면 다시 0부터 3씩 증가되어 열이 추가됨

--13_36
--시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

--13_38
--EMP테이블의 동의어 생성하기
CREATE SYNONYM E FOR EMP;

--13_39
SELECT * FROM E;

--13_40
--SYNONYM 삭제하기
DROP SYNONYM E;

SELECT * FROM EMP;


--13_QUIZ
--Q1
CREATE TABLE EMPIDX
AS SELECT * FROM EMP
WHERE 1<>1;
SELECT * FROM EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO
ON EMPIDX(EMPNO);

SELECT * FROM USER_IND_COLUMNS;