
--14_1
--테이블을 생성할때 not null 설정하기
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20));
    
DESC TABLE_NOTNULL;

--ALTER명령어로 열 이름 수정하기
ALTER TABLE TABLE_NOTNULL
RENAME COLUMN LOGIN_PW TO LOGIN_PWD;

--14_2
--제약 조건이 NOTNULL인 열에 NULL값 넣어보기 (에러)
INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('TEST_ID_01',NULL,'010-1111-1234');

--14_3
--제약 조건이 없는 TEL에 NULL값 넣기
INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD)
VALUES ('TEST_ID_01','1234');

SELECT * FROM TABLE_NOTNULL;

--14_4
--NOT NULL 제약 조건이 지정된 열 데이터를 NULL값으로 업데이트 하기
UPDATE TABLE_NOTNULL
SET LOGIN_PWD = NULL
WHERE LOGIN_ID = 'TEST_ID_01';

--14_5
--제약사항관련 데이터 사전
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME
FROM USER_CONSTRAINTS;

--14_6
--제약 조건 이름을 명시적 작성은 CONSTRAINT 사용자지정이름 제약조건 종류
CREATE TABLE TABLE_NOTNULL2(
    LOGIN_ID VARCHAR(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
    LOGIN_PWD VARCHAR(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
    TEL VARCHAR(20));

SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME
FROM USER_CONSTRAINTS;

--14_7
--NOT NULL 제약 조건의 추가는 ALTER명령어와 MODIFY 키워드를 사용함
ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);
--이미 NULL값이 들어가 있으므로 제약 조건이 추가되지 않음

--14_8
--기존 TEL열을 NULL값이 아닌 데이터로 수정하기
UPDATE TABLE_NOTNULL
SET TEL = '010-1234-1234'
WHERE LOGIN_ID = 'TEST_ID_01';

SELECT * FROM TABLE_NOTNULL;

--14_9
--14_7에서 실패했던 TEL열에 NOT NULL제약 조건 지정
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE ,TABLE_NAME
FROM USER_CONSTRAINTS;

--14_10
--제약 조건에 이름 부여
ALTER TABLE TABLE_NOTNULL2
MODIFY (TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);

--14_11
DESC TABLE_NOTNULL2;

--14_12
--생성한 제약 조건의 이름 변경하기
ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TABLNN2_TEL_NN TO TBLNN2_TEL_NN;

--14_13
ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TBLNN2_TEL_NN; --NOT NULL에서 NULL로 변경은 문제없음 ( NULL은 모두 값 허용)

DESC TABLE_NOTNULL2;